services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: unless-stopped
    env_file:
      - .env

    # Expose port to other containers only, not host
    expose:
      - "8000"
    networks:
      - proxy-tier
